### ISSUE TITLE
【功能】关于api，想和之前一样可以通过镜像环境变量来配置accesstoken，而无需手动发送

### ISSUE THREAD

**Issue by 14790897** [pandora-next/deploy#204]
像之前这样的
```
  pandora:
    image: pengzhile/pandora
    environment:
      - PANDORA_SERVER=${PANDORA_SERVER}
      - PANDORA_ACCESS_TOKEN=${PANDORA_ACCESS_TOKEN}
    expose:
      - "8008"
```
