### ISSUE TITLE
【求助】一直提示Ping remote server failed

### ISSUE THREAD

**Issue by anooki-c** [pandora-next/deploy#238]
部署完成后，8181页面打不开，后台提示Ping remote server failed

日志内容：
PandoraNext  | 2023/12/02 14:56:30 Reading local tokens from /data/tokens.json
PandoraNext  | 2023/12/02 14:56:30 Loaded 2 tokens
PandoraNext  | 2023/12/02 14:56:30 Loaded 0 shared tokens
PandoraNext  | 2023/12/02 14:56:30 ============================================================
PandoraNext  | 2023/12/02 14:58:37 Ping remote server failed

部署环境：
群晖 docker

docker-compse代码：

```
ersion: '3'
services:
  pandora-next:
    image: pengzhile/pandora-next
    container_name: PandoraNext
    network_mode: bridge
    restart: always
    ports:
      - "29988:8181"
    volumes:
      - ./data:/data
      - ./sessions:/root/.cache/PandoraNext
```
config.json

```
{
  "loginUsername": "root",
  "isolated_conv_title": "*",
  "public_share": false,
  "whitelist": null,
  "server_tokens": true,
  "timeout": 600,
  "autoToken_url": "default",
  "site_password": "123456",
  "bind": "0.0.0.0:8181",
  "setup_password": "123456",
  "captcha": {
    "oai_username": false,
    "site_key": "",
    "provider": "",
    "site_secret": "",
    "setup_login": false,
    "site_login": false,
    "oai_password": false
  },
  "license_id": "*****",
  "containerName": "PandoraNext",
  "loginPassword": "123456",
  "tls": {
    "key_file": "",
    "cert_file": "",
    "enabled": false
  },
  "proxy_url": "",
  "cookiesSetupPassword": "_Secure-next-auth.setup-password",
  "proxy_api_prefix": "pandoraapi1",
  "getTokenPassword": "123456"
}
```

湖北电信动态公网ip
