### ISSUE TITLE
【BUG】ping remote server failed

### ISSUE THREAD

**Issue by moecly** [pandora-next/deploy#351]
**描述错误**
docker下无法正常部署

**复现步骤**
```
version: '3'
services:
  pandora-next:
    image: pengzhile/pandora-next
    container_name: PandoraNext
    network_mode: bridge
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - ./data:/data
      - ./sessions:/root/.cache/PandoraNext
```

**截图**
![image](https://github.com/pandora-next/deploy/assets/69760249/1236910c-296b-4228-ae13-689a2f5505ce)

**服务器（请完成以下信息）：**
 - 操作系统：ubuntu
 - 版本：22
 - 架构：arm64

**附加上下文**
dns已配置，似乎是docker时区导致的，本地正常部署
