### ISSUE TITLE
【功能】docker部署的文档中增加  /etc/localtime 映射，让容器时区与主机一致

### ISSUE THREAD

**Issue by huximi** [pandora-next/deploy#396]
**您的功能请求是否与问题有关？请描述。**
docker部署的文档中增加  /etc/localtime 映射，让容器时区与主机一致

**描述您想要的解决方案**
docker部署的文档优化一下，增加时区同步，如下：
```
version: '3'
services:
  pandora-next:
    image: pengzhile/pandora-next:latest
    container_name: PandoraNext
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - ./data:/data
      - ./sessions:/root/.cache/PandoraNext
      - /etc/localtime:/etc/localtime:ro
```
