### ISSUE TITLE
测试了下，docker compose测试完美。nginx和pandoranext均为docker版本写一下配置：

### ISSUE THREAD

**Issue by yefeiyu** [pandora-next/deploy#425]
测试了下，docker compose测试完美。nginx和pandoranext均为docker版本写一下配置：
文件夹：
├── data
│   ├── config.json
│   └── tokens.json
└── docker-compose.yml

首先 config.json写法：
```
{
  "bind": "0.0.0.0:8181",
  "timeout": 600,
  "proxy_url": ""
}
```
注意，请留意这里的8181

tokens.json写法
```
{
  "test2": {
    "token": "fk-stsiadoah6HFJSAmowkt2iuR3rQvcpLpDwxQnmo9824",
    "password": "12345"
  }
}
```
你可以写多个token，注意语法

最后是yml文件
```

version: '3'

services:
  pandora-next:
    image: pengzhile/pandora-next
    container_name: PandoraNext
    network_mode: bridge
    restart: always
    environment:
      - PANDORA_NEXT_LICENSE=eyJhbGciO（需要dd始皇gg）
    volumes:
      - ./data:/data
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
```
这里我说明一下， nginx_network网络包含nginx，因为我不想让pandoranext暴露端口，所以我没设置port字段，但这个nginx_network你需要自己创建，然后让nginx也加入这个网络，至少当你运行
 docker network inspect nginx_network
命令后有  "5ae90c7b2397d580ea71dfc98143a56b670d576f3953371234a6e16ca6a0e862": {
                "Name": "nginx1（你的nginx容器）",
                "EndpointID": "b0b32201d7cf909fda32bd235c767bbc422bfb1e953ef248a5b79bf4d3bd31bd",
                "MacAddress": "02:52:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "a06fc0df70f6836a569bf826185f013bbf13e47c6b3214759ea4b22474f2fe7a": {
                "Name": "PandoraNext",
                "EndpointID": "66191a12ca4c5f49bf67fb3f2c816bc39415c76fa1ad20bc92cd94df0c98ff0f",
                "MacAddress": "02:52:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },类似结果

至此，完成pandoranext部署，可以直接部署，但是由于没有暴露端口，你无法直接ip:8181访问，需要nginx反代，
```
#erver block
server {
    listen 80;
    server_name chat1.com（也就是你的域名）;

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server block
server {
    listen 443 ssl;
    server_name chat1.com（也就是你的域名）;

    ssl_certificate /etc/nginx/cert/url.com.pem（你的证书）;
    ssl_certificate_key /etc/nginx/cert/url.com.key（你的证书）;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;



    location / {
        proxy_pass http://PandoraNext:8181;  # 将请求代理到PandoraNext服务
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }



    # Uncomment if needed
    # location = /favicon.ico {
    #    log_not_found off;
    #    access_log off;
    # }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```

这样就能在访问chat1.com的时候使用pandora了，而且没有暴露端口。
注意在nginx的8181，这个就是上面config的端口号，需要保持一致

_Originally posted by @yfh667 in https://github.com/pandora-next/deploy/issues/6#issuecomment-1809814259_
