### ISSUE TITLE
docker 部署尝试多次报错 Unable to verify the server's license: illegal base64 data at input byte

### ISSUE THREAD

**Issue by layui0320** [pandora-next/deploy#53]
Docker Version
```
Client:
 Version:           20.10.5+dfsg1
 API version:       1.41
 Go version:        go1.15.15
 Git commit:        55c4c88
 Built:             Mon May 30 18:34:49 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.5+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.15
  Git commit:       363e9a8
  Built:            Mon May 30 18:34:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.13~ds1
  GitCommit:        1.4.13~ds1-1~deb11u2
 runc:
  Version:          1.0.0~rc93+ds1
  GitCommit:        1.0.0~rc93+ds1-5+deb11u2
 docker-init:
  Version:          0.19.0
  GitCommit:
```

Docker Compose Version
`Docker Compose version v2.12.2`

v0.1.1以及最新v0.1.2版本都是一样的提示： Unable to verify the server's license: illegal base64 data at input byte

已经将license.jwt文件内容粘贴到PANDORA_NEXT_LICENSE变量的。
```
    environment:
      - PANDORA_NEXT_LICENSE=Token

```
```
    environment:
      - PANDORA_NEXT_LICENSE=“Token”

```
两种方式都不行。

完整日志：
```
2023/11/17 09:50:03 Unable to verify the server's license: illegal base64 data at input byte 0
2023/11/17 09:50:04 Unable to verify the server's license: illegal base64 data at input byte 0
2023/11/17 09:50:04 Unable to verify the server's license: illegal base64 data at input byte 0
2023/11/17 09:50:05 Unable to verify the server's license: illegal base64 data at input byte 0
2023/11/17 09:50:07 Unable to verify the server's license: illegal base64 data at input byte 0
2023/11/17 09:50:09 Unable to verify the server's license: illegal base64 data at input byte 0
```

**Comment by doherty88** [comment]
environment:
      - PANDORA_NEXT_LICENSE=“Token”
      
      你这引号是不是中文的引号？换成英文的试试

**Comment by taozihk** [comment]
兄弟，非得用docker？

**Comment by layui0320** [comment]
> environment: - PANDORA_NEXT_LICENSE=“Token”
> 
> ```
>   你这引号是不是中文的引号？换成英文的试试
> ```

感谢回复，我再次确认了docker-compose.yml的文件内容，确实是英文的双引号，以下是cat命令输出的内容：

```
version: '3'
services:
  pandora-next:
    image: pengzhile/pandora-next
    container_name: PandoraNext
    network_mode: bridge
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - /root/pandora-next/data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PANDORA_NEXT_LICENSE="eyJhbGqZnFDtQ#"
```

jwt token关键信息中间已省略。
